##
# This file is part of the Metasploit Framework and may be subject to 
# redistribution and commercial restrictions. Please see the Metasploit
# Framework web site for more information on licensing and terms of use.
# http://metasploit.com/projects/Framework/
##

require 'msf/core'

class Metasploit3 < Msf::Auxiliary

	include Msf::Exploit::Remote::HttpClient
	include Msf::Auxiliary::Scanner

	def initialize
		super(
			'Name'        => 'Oracle Application Server Check',
			'Version'     => '$Revision:$',
			'Description' => " This module scans for common files on an Oracle Application Server and Oracle Database Server.  If you are having issues. set VERBOSE to TRUE to see all error codes.",
			'References'  =>
			[
				[ 'URL', 'www.ngssoftware.com/papers/hpoas.pdf' ],
			],
			'Author'      => [ 'MC', 'CG' ],
			'License'     => MSF_LICENSE
			)

	register_options(
			[
				Opt::RPORT(80),
				OptBool.new('DEMOS', [ true, 'Enable checks for all the demo pages', false ]),
				OptBool.new('VERBOSE', [ true, 'Show all errror codes or just 200/302', false ]),
			], self.class)
	end

	def run_host(ip)

		#{ :path => "/_pages/", :type => "GET", :vuln => "Index of demo pages", :sig => ""},
		checks = [
			{ :path => "/_pages/", :type => "GET", :vuln => "Index of demo pages--CVE-2002-0565"},
		  	{ :path => "/_pages/_webapp/_admin/_showpooldetails.java", :type => "GET", :vuln => "CVE-2002-0565"},
			{ :path => "/_pages/_webapp/_admin/_showjavartdetails.java", :type => "GET", :vuln => "CVE-2002-0565"},
			{ :path => "/_pages/_webapp/_jsp/", :type => "GET", :vuln => "CVE-2002-0565"},
			{ :path => "/_pages/_demo/", :type => "GET", :vuln => "CVE-2002-0565"},
			{ :path => "/_pages/_demo/_sql/_pages/", :type => "GET", :vuln => "CVE-2002-0565"},
			{ :path => "/OA_HTML/AppsLocalLogin.jsp", :type => "GET", :vuln => "Oracle E-business Server -- Use Ebiz Scanner"},
			{ :path => "/admin/", :type => "GET", :vuln => ""},
			{ :path => "/admin_/", :type => "GET", :vuln => ""},
			{ :path => "/adminoc4j", :type => "GET", :vuln => ""},
			{ :path => "/appdet.html", :type => "GET", :vuln => ""},
			{ :path => "/AQApp", :type => "GET", :vuln => ""},
			{ :path => "/AQApp/", :type => "GET", :vuln => ""},
			{ :path => "/aplogon.html", :type => "GET", :vuln => ""},
			{ :path => "/assistants/", :type => "GET", :vuln => ""},
			{ :path => "/backup_restore/", :type => "GET", :vuln => ""},
			{ :path => "/bc4j.html", :type => "GET", :vuln => "Business Components for Java"},
			{ :path => "/bc4jadmin/bc4jadmin.htm", :type => "GET", :vuln => "BC4J Admin Utility"},
			{ :path => "/bc4jdoc/", :type => "GET", :vuln => "BC4J Documentation"},
			{ :path => "/bc4jdoc/rt/index.html", :type => "GET", :vuln => "BC4J Documentation"},
			{ :path => "/BC4J/", :type => "GET", :vuln => "BC4J Documentation"},
			{ :path => "/BC4J", :type => "GET", :vuln => "BC4J Documentation"},
			{ :path => "/bc4jdoc/setup.html", :type => "GET", :vuln => "Online Orders Demo Setup"},
			{ :path => "/BPELConsole/", :type => "GET", :vuln => "BPEL Console Pages"},
			{ :path => "/BPELConsole/login.jsp", :type => "GET", :vuln => "BPEL Console Login"},
			{ :path => "/BPELAdmin/", :type => "GET", :vuln => "BPEL Admin Pages"},
			{ :path => "/BPELAdmin/server.jsp", :type => "GET", :vuln => "BPEL Admin Login"},
			{ :path => "/BPELAdmin/login.jsp", :type => "GET", :vuln => "BPEL Admin Login"},
			{ :path => "/callerInfo/", :type => "GET", :vuln => ""},
			{ :path => "/callerInfo/callerInfo/", :type => "GET", :vuln => "JAAS Provider callerInfo Demo"},
			{ :path => "/callerInfo/callerInfoA", :type => "GET", :vuln => "JAAS Provider callerInfo Demo"},
			{ :path => "/callerInfo/callerInfoB", :type => "GET", :vuln => "JAAS Provider callerInfo Demo"},
			{ :path => "/callerInfo/README.txt", :type => "GET", :vuln => "Readme for JAAS Provider callerInfo Demo"},
			{ :path => "/cartx/owa", :type => "GET", :vuln => ""},
			{ :path => "/ccore/", :type => "GET", :vuln => ""},
			{ :path => "/cgi-bin/", :type => "GET", :vuln => ""},
			{ :path => "/cgi-bin/printenv", :type => "GET", :vuln => "Prints Oracle HTTP Environment Variables"},
			{ :path => "/cgi-bin/printenv.tmp", :type => "GET", :vuln => ""},
			{ :path => "/cgi-bin/test-cgi", :type => "GET", :vuln => ""},
			{ :path => "/config.xml", :type => "GET", :vuln => ""},
			{ :path => "/Consumer", :type => "GET", :vuln => ""},
			{ :path => "/Consumer/HotelAdmin.jsp", :type => "GET", :vuln => ""},
			{ :path => "/content/index.jspx", :type => "GET", :vuln => "Oracle Content Database"},
			{ :path => "/content/ws/RemoteLoginManager", :type => "POST", :vuln => "Remote Login Manger?"},
			{ :path => "/content/ws/SessionManager", :type => "GET", :vuln => ""},
			{ :path => "/csportlet/providers/", :type => "GET", :vuln => "JPDK Test Page"},
			{ :path => "/dav", :type => "GET", :vuln => "Check for writeable dav directory"},
			{ :path => "/dav/", :type => "GET", :vuln => "Check for writeable dav directory"},
			{ :path => "/dav_portal/portal/", :type => "GET", :vuln => "Check for writeable dav directory--check for dav bypass"},
			{ :path => "/dav_public", :type => "GET", :vuln => "Check for writeable dav directory"},
			{ :path => "/dav_public/", :type => "GET", :vuln => "Check for writeable dav directory"},
			{ :path => "/demo/sql/jdbc/JDBCQuery.jsp", :type => "GET", :vuln => "Run SQL Cmds"},
			{ :path => "/dev60cgi/f60cgi", :type => "GET", :vuln => "Oracle Forms 6i"},
			{ :path => "/dev60cgi/f60cgi?form=test.fmx", :type => "GET", :vuln => "Oracle Forms 6i"},
			{ :path => "/dev60cgi/ifcgi60.exe", :type => "GET", :vuln => "Oracle Forms 6i"},
			{ :path => "/dev60cgi/rwcgi60", :type => "GET", :vuln => "Oracle Reports"},
			{ :path => "/diagnostics/", :type => "GET", :vuln => ""},
			{ :path => "/discoverer/viewer", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/viewer_files/help/en/edit_parameters.htm", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/plus", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/app/cec?event=createConnection&clientType=plus", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/plus#Connect%20Directly", :type => "GET", :vuln => "Oracle Application Server Discoverer -- show connections"},
			{ :path => "/discoverer/app/about?event=showAboutPage", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/app/connection?event=displayConnections", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/app/export?event=startExport", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/app/cec?event=createConnection&clientType=viewer", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/app/connection?event=displayConnections#Connect%20Directly", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/intro/html/disc_demo_intro.htm", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/intro/html/disc_demo_custom.htm", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/discoverer/common/help/en/connections.htm", :type => "GET", :vuln => "Oracle Application Server Discoverer"},
			{ :path => "/dms/AggreSpy", :type => "GET", :vuln => "Oracle DMS Metrics"},
			{ :path => "/dms/DMSDump", :type => "GET", :vuln => "Oracle DMS Current Values"},
			{ :path => "/dms0", :type => "GET", :vuln => "Oracle DMS Dump"},
			{ :path => "/dms0/", :type => "GET", :vuln => "Oracle DMS Dump"},
			{ :path => "/dsa/", :type => "GET", :vuln => ""},
			{ :path => "/esb/", :type => "GET", :vuln => ""},
			{ :path => "/em", :type => "GET", :vuln => "Oracle Enterprise Manager"},
			{ :path => "/em/", :type => "GET", :vuln => "Oracle Enterprise Manager"},
			{ :path => "/em/dynamicImage/emSDK/chart/EmChartBean", :type => "GET", :vuln => "Oracle Enterprise Manager"},
			{ :path => "/emd/dynamicImage/emSDK/chart/EmChartBean", :type => "GET", :vuln => "Oracle Enterprise Manager"},
			{ :path => "/em/dynamicImage/emSDK/chart/EmChartBean?beanId=\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\boot.ini", :type => "GET", :vuln => "Oracle Enterprise Manager"},
			{ :path => "/emd/dynamicImage/emSDK/chart/EmChartBean?beanId=\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\boot.ini", :type => "GET", :vuln => "Oracle Enterprise Manager"},
			{ :path => "/examples/jsp/", :type => "GET", :vuln => "Default JSP examples on a 10.1 Oracle"},
			{ :path => "/examples/servlets/", :type => "GET", :vuln => "Default JSP examples on a 10.1 Oracle"},
			{ :path => "/FAQApp", :type => "GET", :vuln => ""},
			{ :path => "/fastcgi/", :type => "GET", :vuln => "Fastcgi Developer's Kit Index Page"},
			{ :path => "/fcgi-bin/", :type => "GET", :vuln => ""},
			{ :path => "/fcgi-bin/echo", :type => "GET", :vuln => ""},
			{ :path => "/fcgi-bin/echo.exe", :type => "GET", :vuln => ""},
			{ :path => "/fcgi-bin/echo2", :type => "GET", :vuln => ""},
			{ :path => "/fcgi-bin/echo2.exe", :type => "GET", :vuln => ""},
			{ :path => "/fcgi-bin/printenv", :type => "GET", :vuln => ""},
			{ :path => "/file.xsql?name=foobar", :type => "GET", :vuln => "See HPOAS page 14"},
			{ :path => "/forms/lservlet", :type => "GET", :vuln => "Oracle Forms Service Status"},
			{ :path => "/forms/jinitiator/us/jinit_download.htm", :type => "GET", :vuln => "Oracle Forms"},
			{ :path => "/forms/frmservlet?form=test.fmx", :type => "GET", :vuln => "Oracle Forms"},			
			{ :path => "/forms90/f90servlet?form=test.fmx", :type => "GET", :vuln => "Oracle Forms 9i"},
			{ :path => "/forms90/f90servlet", :type => "GET", :vuln => "Oracle Forms 9i"},
			{ :path => "/f60cgi.exe", :type => "GET", :vuln => "Oracle Forms"},
			{ :path => "/f60servlet", :type => "GET", :vuln => "Oracle Forms"},
			{ :path => "/globals.jsa", :type => "GET", :vuln => "CVE-2002-0562"},
			{ :path => "/has/", :type => "GET", :vuln => ""},
			{ :path => "/hdemo", :type => "GET", :vuln => ""},
			{ :path => "/help/index.htm", :type => "GET", :vuln => "Help Index"},
			{ :path => "/HotelService", :type => "GET", :vuln => ""},
			{ :path => "/iaspt/", :type => "GET", :vuln => ""},
			{ :path => "/imtapp/app/prelogin.uix", :type => "GET", :vuln => "Oracle Real-Time Collaboration"},
			{ :path => "/imtapp/app/arc_pub.uix", :type => "GET", :vuln => "Oracle Real-Time Collaboration"},
			{ :path => "/imtapp/app/home.uix?siteID=", :type => "GET", :vuln => "Oracle Real-Time Collaboration"},
			{ :path => "/imtapp/app/gbl_contact_us.uix", :type => "GET", :vuln => "Oracle Real-Time Collaboration"},
			{ :path => "/imtapp/app/pubschconf.uix", :type => "GET", :vuln => "Oracle Real-Time Collaboration"},
			{ :path => "/imthelp/help/", :type => "GET", :vuln => ""},
			{ :path => "/install.platform/", :type => "GET", :vuln => ""},
			{ :path => "/inTellectPRO.jsp", :type => "GET", :vuln => ""},
			{ :path => "/install/", :type => "GET", :vuln => ""},
			{ :path => "/isqlplus", :type => "GET", :vuln => "Oracle DB iSqlPlus Login"},
			{ :path => "/isqlplus/", :type => "GET", :vuln => "Oracle DB iSqlPlus Login"},
			{ :path => "/IsWebCacheWorking/", :type => "GET", :vuln => "Oracle Webcache"},
			{ :path => "/IsWebCacheWorking/jesi_template.jsp", :type => "GET", :vuln => "Oracle Webcache"},
			{ :path => "/iASDemos.htm", :type => "GET", :vuln => ""},
			{ :path => "/javacache/", :type => "GET", :vuln => ""},
			{ :path => "/J2EE.htm", :type => "GET", :vuln => ""},
			{ :path => "/J2EEandIA.htm", :type => "GET", :vuln => ""},
			{ :path => "/javavm/", :type => "GET", :vuln => ""},
			{ :path => "/jdbc/", :type => "GET", :vuln => ""},
			{ :path => "/jmsws1", :type => "GET", :vuln => ""},
			{ :path => "/jmsws2", :type => "GET", :vuln => ""},
			{ :path => "/jmsws1.ear", :type => "GET", :vuln => ""},
			{ :path => "/jocdemo/servlet/IsCacheWorking", :type => "GET", :vuln => ""},
			{ :path => "/jre/", :type => "GET", :vuln => ""},
			{ :path => "/jserv", :type => "GET", :vuln => ""},
			{ :path => "/jserv/status?module=127.0.0.1", :type => "GET", :vuln => ""},
			{ :path => "/jserv/engine/0", :type => "GET", :vuln => ""},
			{ :path => "/jservdocs/", :type => "GET", :vuln => "Apache JServ Documentation"},
			{ :path => "/jinitiator/jinit_download.htm", :type => "GET", :vuln => "Jinitiator download page"},
			{ :path => "/jinitiator/us/jinit_download.htm", :type => "GET", :vuln => "Jinitiator download page"},
			{ :path => "/jsp/", :type => "GET", :vuln => ""},
			{ :path => "/jsp_backup/", :type => "GET", :vuln => ""},
			{ :path => "/jspdocs/javadoc", :type => "GET", :vuln => "jsp documentation, may have default DB version"},
			{ :path => "/jspdocs/", :type => "GET", :vuln => "JSP Documentation"},
			{ :path => "/jspdocs/index.html", :type => "GET", :vuln => "JSP Documentation"},
			{ :path => "/lbs/", :type => "GET", :vuln => ""},
			{ :path => "/ldap/", :type => "GET", :vuln => ""},
			{ :path => "/log/", :type => "GET", :vuln => ""},
			{ :path => "/logs", :type => "GET", :vuln => ""},
			{ :path => "/master/", :type => "GET", :vuln => ""},
			{ :path => "/mesg/", :type => "GET", :vuln => ""},
			{ :path => "/myapp", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/myapp/", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/mydad", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/mydad/", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/mod_ose_docs/", :type => "GET", :vuln => "Apache Module for Oracle Servlet Engine Documentation"},
			{ :path => "/mod_ose.html", :type => "GET", :vuln => "Apache Module for Oracle Servlet Engine Documentation"},
			{ :path => "/nls", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/nls/", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/NFIntro.htm", :type => "GET", :vuln => ""},
			{ :path => "/OA_HTML/", :type => "GET", :vuln => "Oracle E-business Server -- Use Ebiz Scanner"},
			{ :path => "/oa_servlets/AppsLogin", :type => "GET", :vuln => "Oracle E-business Server -- Use Ebiz Scanner"},
			{ :path => "/oa_servlets/oracle.apps.fnd.sso.FNDSSOLogoutRedirect", :type => "GET", :vuln => "Oracle E-business Server -- Check 302 for DAD"},
			{ :path => "/oiddas/", :type => "GET", :vuln => "Oracle Directory Services"},
			{ :path => "/oiddas/ui/oracle/ldap/das/mypage/ViewMyPage", :type => "GET", :vuln => "Oracle Directory Services"},
			{ :path => "/oiddas/ui/oracle/ldap/das/directory/DASUserMgmtDir", :type => "GET", :vuln => "Oracle Directory Services"},
			{ :path => "/oiddas/ui/oracle/ldap/das/conf/DASGeneralConf?route=true", :type => "GET", :vuln => "Oracle Directory Services"},
			{ :path => "/oiddas/ui/oracle/ldap/das/subscriber/DASSubscriberLOV", :type => "GET", :vuln => "Oracle Directory Services"},
			{ :path => "/oiddas/oiddashome.uix?event=ssologin", :type => "GET", :vuln => "Oracle Directory Services"},
			{ :path => "/oiddas/ui/", :type => "GET", :vuln => "Oracle Directory Services"},
			{ :path => "/onlineorders_html/", :type => "GET", :vuln => "Demo Page"},
			{ :path => "/onlineorders/main.jsp", :type => "GET", :vuln => "Demo Page"},
			{ :path => "/onlineorders/signon.jsp", :type => "GET", :vuln => "Demo Page"},
			{ :path => "/onlineorders/main.jsp", :type => "GET", :vuln => "Demo Page"},
			{ :path => "/OnlineOrders_html/", :type => "GET", :vuln => "Demo Page"},
			{ :path => "/OnlineOrders_html/login.jsp", :type => "GET", :vuln => "Demo Page"},
			{ :path => "/oprocmgr-service", :type => "GET", :vuln => ""},
			{ :path => "/oprocmgr-status", :type => "GET", :vuln => "Process Status"},
			{ :path => "/orasso", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/orasso/", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/orasso/orasso.home", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/ord/", :type => "GET", :vuln => ""},
			{ :path => "/oui/", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/email/sendmail.jsp", :type => "GET", :vuln => ""},
			{ :path => "/owa_util.cellsprint?p_theQuery=select+1+from+dual", :type => "GET", :vuln => "Portal Injection"},
			{ :path => "/owa_util.listprint?p_theQuery=select+1+from+dual", :type => "GET", :vuln => "Portal Injection"},
			{ :path => "/owa_util.show_query_columns?ctable=sys.dba_users", :type => "GET", :vuln => "Portal Inejction"},
			{ :path => "/owa_util.showsource?cname=books", :type => "GET", :vuln => "Portal, Vulnerable Package (Show Source)"},
			{ :path => "/owm/", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/ows-bin/", :type => "GET", :vuln => "Default DAD -- Should 302 Your Request"},
			{ :path => "/ows-bin/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/admin_/gateway.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/admin_/globalsettings.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/admin_/globalsettings.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/admin_/dadentries.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/admin_/cache.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/app/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/banking/admin_/", :type => "GET", :vuln => "Oracle Portal"},		
			{ :path => "/ows-bin/cartx/owa/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/dad/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/db/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/owa/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/htmldb/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/myapp/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/mydad/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/orasso/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/online/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/ows-binqlapp/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal2/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal30/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal30_sso/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal306/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal309/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/qa/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/real/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/sample/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/simpledad/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/ssodad/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/test/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/app", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/banking/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/cartx/owa", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/dad", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/db", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/owa", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/htmldb", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/myapp", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/mydad", :type => "GET", :vuln => "Oracle Portal"},	
			{ :path => "/ows-bin/myDAD", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/orasso", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/online", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/ows-binqlapp", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal2", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal30", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal30_sso", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal306", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/portal309", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/qa", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/real", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/sample", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/simpledad", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/simpledad/sample.home", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ows-bin/ssodad", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/perl/", :type => "GET", :vuln => ""},
			{ :path => "/perl/printenv", :type => "GET", :vuln => "Oracle Environmental Variables"},
			{ :path => "/perl-status", :type => "GET", :vuln => ""},
			{ :path => "/pls", :type => "GET", :vuln => "modplsql gateway"},
			{ :path => "/pls/", :type => "GET", :vuln => "modplsql gateway"},
			{ :path => "/pls/apex", :type => "GET", :vuln => "Oracle Apex"},
			{ :path => "/pls/admin_/gateway.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/admin_/globalsettings.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/admin_/help/..%255Cplsql.conf", :type => "GET", :vuln => ""},
			{ :path => "/pls/admin_help/%252F..%252Fplsql.conf", :type => "GET", :vuln => ""},
			{ :path => "/pls/banking/account.welcome", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/bookstore", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/cartx/owa", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/cartx/owa/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/cfg/admin_?schema=app", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/classic/admin_/gateway.htm?schema=", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/classic/admin_/globalsettings.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/classic/admin_/dadentries.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/classic/admin_/cache.htm", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/help/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/htmldb", :type => "GET", :vuln => "Oracle Apex"},
			{ :path => "/pls/htmldb/htmldb", :type => "GET", :vuln => "Oracle Apex"},
			{ :path => "/pls/htmldb/apex_admin", :type => "GET", :vuln => "Oracle Apex"},
			{ :path => "/pls/myapp", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/myapp/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/mydad", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/mydad/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/orasso", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/orasso/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/orasso/orasso.wwsso_app_admin.ls_login?", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/orasso/orasso.home", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/plsqlapp", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/plsqlapp/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal30", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal30/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal30_sso", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal30_sso/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal306", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal306/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal309", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/portal309/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/prod/fnd_web.ping", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/qa", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/qa/admin_/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/wf/wfa_html.home", :type => "GET", :vuln => "Oracle Portal--Oracle Workflow"},
			{ :path => "/pls/wf/wf_demo.home", :type => "GET", :vuln => "Oracle Portal--Oracle Workflow"},
			{ :path => "/pls/cs_wf/wfa_html.home", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/wfa/wfa_html.home", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/pls/Workflow/wfa_html.home", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/plsql/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/plsqlapp/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portal/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portal/pls/portal", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portal/page", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portal/page?_pageid=6,1,6_13&_dad=portal&_schema=PORTAL", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portal30", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portal30_sso", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portal306", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portal309", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/portalTools/", :type => "GET", :vuln => ""},
			{ :path => "/portalTools/omniPortlet/providers/omniPortlet", :type => "GET", :vuln => ""},
			{ :path => "/portalTools/webClipping/providers/webClipping", :type => "GET", :vuln => ""},
			{ :path => "/portalTools/sample/providers/omniPortletSample", :type => "GET", :vuln => ""},
			{ :path => "/precomp/", :type => "GET", :vuln => "Oracle Portal"},
			{ :path => "/ptg/rm", :type => "GET", :vuln => "Oracle Wireless Portal"},
			{ :path => "/ptg_upgrade_pkg.log", :type => "GET", :vuln => ""},
			{ :path => "/qa", :type => "GET", :vuln => "modplsql gateway"},
			{ :path => "/rdbms/", :type => "GET", :vuln => ""},
			{ :path => "/real", :type => "GET", :vuln => ""},
			{ :path => "/recomp_exit.dyn", :type => "GET", :vuln => ""},
			{ :path => "/relnotes", :type => "GET", :vuln => ""},
			{ :path => "/repdemo/index.html", :type => "GET", :vuln => "Default Content"},
			{ :path => "/repdemo/runJSPIAS.html", :type => "GET", :vuln => "Default Content"},
			{ :path => "/repdemo/runrepIAS.html", :type => "GET", :vuln => ""},
			{ :path => "/reports/examples/Tools/test.jsp", :type => "GET", :vuln => "Oracle Reports has XSS test: test.jsp?repprod\"<script>alert( document.cookie );</script> "},
			{ :path => "/reports/rwservlet", :type => "GET", :vuln => "Oracle Reports URLS with sensitive info"},
			{ :path => "/reports/rwservlet/showenv", :type => "GET", :vuln => "Oracle Reports URLS with sensitive info"},
			{ :path => "/reports/rwservlet/showmap", :type => "GET", :vuln => "Oracle Reports URLS with sensitive info"},
			{ :path => "/reports/rwservlet/showjobs", :type => "GET", :vuln => "Oracle Reports URLS with sensitive info"},
			{ :path => "/reports/rwservlet/showmap?server=myserver", :type => "GET", :vuln => "Oracle Reports"},
			{ :path => "/reports/rwservlet/killjobid", :type => "GET", :vuln => "Oracle Reports"},
			{ :path => "/reports/rwservlet/parsequery", :type => "GET", :vuln => "Oracle Reports"},
			{ :path => "/reports/rwservlet/showauth", :type => "GET", :vuln => "Oracle Reports"},
			{ :path => "/reports/rwservlet/delauth", :type => "GET", :vuln => "Oracle Reports"},
			{ :path => "/reports/rwservlet/getserverinfo", :type => "GET", :vuln => "Oracle Reports"},
			{ :path => "/reports/rwservlet/killengine", :type => "GET", :vuln => "Oracle Reports"},
			{ :path => "/richtextportlet/info", :type => "GET", :vuln => ""},
			{ :path => "/root.sh", :type => "GET", :vuln => ""},
			{ :path => "/runqianprovider/providers/", :type => "GET", :vuln => "RunQian Portlet"},
			{ :path => "/ruleauthor/", :type => "GET", :vuln => ""},
			{ :path => "/sample", :type => "GET", :vuln => ""},
			{ :path => "/sejb_webservices", :type => "GET", :vuln => ""},
			{ :path => "/sejb_webservices/HelloService?proxy_jar", :type => "GET", :vuln => ""},
			{ :path => "/sejb_webservices/HelloService?WSDL", :type => "GET", :vuln => ""},
			{ :path => "/server-info", :type => "GET", :vuln => "Apache Info"},
			{ :path => "/server-status", :type => "GET", :vuln => "Apache Server Status"},
			{ :path => "/servlet", :type => "GET", :vuln => ""},
			{ :path => "/servlet/DMSDump", :type => "GET", :vuln => "DMS: Current Metric Values"},
			{ :path => "/servlet/IsCacheWorking", :type => "GET", :vuln => ""},
			{ :path => "/servlet/IsItWorking", :type => "GET", :vuln => "Jserv status page"},
			{ :path => "/servlets/weboam/oam/oamLogin", :type => "GET", :vuln => ""},
			{ :path => "/servlet/f60servlet", :type => "GET", :vuln => "Oracle Forms 6i Servlet"},
			{ :path => "/servlet/oracle.xml.xsql.XSQLServlet/soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml", :type => "GET", :vuln => "SOAP Configs"},
			{ :path => "/servlet/Oracle.xml.xsql.XSQLServlet/soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml", :type => "GET", :vuln => "SOAP Configs"},
			{ :path => "/servlet/oracle.xml.xsql.XSQLServlet/xsql/lib/XSQLConfig.xml", :type => "GET", :vuln => "XSQL Configs, unfortunately not found returns a 200...manually check"},
			{ :path => "/servlet/Oracle.xml.xsql.XSQLServlet/xsql/lib/XSQLConfig.xml", :type => "GET", :vuln => "XSQL Configs, unfortunately not found returns a 200...manually check"},
			{ :path => "/servlet/Spy", :type => "GET", :vuln => "Oracle DMS Metrics"},
			{ :path => "/simpledad", :type => "GET", :vuln => "Oracle Portal Default DAD"},
			{ :path => "/slax", :type => "GET", :vuln => ""},
			{ :path => "/soap/", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soap/servlet/soaprouter", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soap/servlet/Spy", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soap/admin", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soap/admin/servlet/soaprouter", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soap/admin/servicemanager", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soap/admin/providermanager", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soapbuilder/", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soapbuilder/r2/InteropTest", :type => "GET", :vuln => "Oracle SOAP Servlet"},
			{ :path => "/soapdocs/", :type => "GET", :vuln => "Oracle SOAP Docs"},
			{ :path => "/soapdocs/ReleaseNotes.html", :type => "GET", :vuln => "Oracle SOAP Docs"},
			{ :path => "/soapdocs/webapps/soap/WEB-INF/config/soapConfig.xml", :type => "GET", :vuln => "Oracle SOAP Docs"},
			{ :path => "/sqlj", :type => "GET", :vuln => ""},
			{ :path => "/sqlnet.log", :type => "GET", :vuln => ""},
			{ :path => "/sqlplus", :type => "GET", :vuln => ""},
			{ :path => "/srvm", :type => "GET", :vuln => ""},
			{ :path => "/sso", :type => "GET", :vuln => ""},
			{ :path => "/sso/jsp/login.jsp", :type => "GET", :vuln => "XSS is login.jsp?site2pstoretoken=XSS"},
			{ :path => "/ssodad", :type => "GET", :vuln => "Default DAD"},
			{ :path => "/statefuldocws", :type => "GET", :vuln => ""},
			{ :path => "/statelessdocws", :type => "GET", :vuln => ""},
			{ :path => "/syndication/", :type => "GET", :vuln => ""},
			{ :path => "/sysman/", :type => "GET", :vuln => ""},
			{ :path => "/sysman/reporting/", :type => "GET", :vuln => ""},
			{ :path => "/test/", :type => "GET", :vuln => ""},
			{ :path => "/text/", :type => "GET", :vuln => ""},
			{ :path => "/tmp/", :type => "GET", :vuln => ""},
			{ :path => "/temp/", :type => "GET", :vuln => ""},
			{ :path => "/tmp/", :type => "GET", :vuln => ""},
			{ :path => "/uddi/", :type => "GET", :vuln => "Oracle AS UDDI Registry"},
			{ :path => "/uddi/inquiry", :type => "GET", :vuln => "Oracle AS UDDI Inquiry SOAP End Point"},
			{ :path => "/uddi/publishing", :type => "GET", :vuln => "Oracle AS UDDI Publishing End Point"},
			{ :path => "/uddi/admin", :type => "GET", :vuln => "Oracle AS UDDI Admin End Point"},
			{ :path => "/uddirepl/replication", :type => "GET", :vuln => "Oracle AS UDDI Replication SOAP End Point"},
			{ :path => "/uddirepl/admin/wallet", :type => "GET", :vuln => "Oracle AS UDDI Wallet Password Admin End Point"},
			{ :path => "/uddi/demo/jsp/searchForm.jsp", :type => "GET", :vuln => "UDDI Registry Search/Browse Page"},
			{ :path => "/uix/", :type => "GET", :vuln => ""},
			{ :path => "/tictactoe", :type => "GET", :vuln => ""},
			{ :path => "/tmp/", :type => "GET", :vuln => ""},
			{ :path => "/ultrasearch/", :type => "GET", :vuln => "Oracle Ultra Search Query Applications"},
			{ :path => "/ultrasearch/query/", :type => "GET", :vuln => "Oracle Ultra Search Query Applications"},
			{ :path => "/ultrasearch/query/search.jsp", :type => "GET", :vuln => "Oracle Ultra Search Query Applications"},
			{ :path => "/ultrasearch/query/usearch.jsp", :type => "GET", :vuln => "Oracle Ultra Search Query Applications"},
			{ :path => "/ultrasearch/query/mail.jsp", :type => "GET", :vuln => "Oracle Ultra Search Query Applications"},
			{ :path => "/ultrasearch/query/tag/tsearch.jsp", :type => "GET", :vuln => "Oracle Ultra Search Query Applications"},
			{ :path => "/ultrasearch/query/9i/gsearch.jsp", :type => "GET", :vuln => "Oracle Ultra Search Query Applications"},
			{ :path => "/ultrasearch/query/9i/mail.jsp", :type => "GET", :vuln => "Oracle Ultra Search Query Applications"},
			{ :path => "/ultrasearch/admin/index.jsp", :type => "GET", :vuln => "Oracle Ultra Search Admin Portal"},
			{ :path => "/ultrasearch/admin/control/login.jsp", :type => "GET", :vuln => "Oracle Ultra Search Admin Portal"},
			{ :path => "/upgrade/", :type => "GET", :vuln => ""},
			{ :path => "/wcs/", :type => "GET", :vuln => ""},
			{ :path => "/web_services", :type => "GET", :vuln => ""},
			{ :path => "/web-inf/config.xml", :type => "GET", :vuln => ""},
			{ :path => "/WEB-INF/config.xml", :type => "GET", :vuln => ""},
			{ :path => "/webapp/", :type => "GET", :vuln => ""},
			{ :path => "/webapp/admin/", :type => "GET", :vuln => ""},
			{ :path => "/webapp/admin/bc4jadmin.htm", :type => "GET", :vuln => ""},
			{ :path => "/webapp/admin/showpooldetails.jsp", :type => "GET", :vuln => ""},
			{ :path => "/webapp/admin/showsessiondetails.jsp", :type => "GET", :vuln => ""},
			{ :path => "/webapp/admin/showbc4jrtdetails.jsp", :type => "GET", :vuln => ""},
			{ :path => "/webapp/cabo/", :type => "GET", :vuln => ""},
			{ :path => "/webapp/css/", :type => "GET", :vuln => ""},
			{ :path => "/webapp/jsp/", :type => "GET", :vuln => ""},
			{ :path => "/webapp/images/", :type => "GET", :vuln => ""},
			{ :path => "/webapp/jsimages/", :type => "GET", :vuln => ""},
			{ :path => "/webapp/admin/_pages/_bc4jadmin/", :type => "GET", :vuln => ""},
			{ :path => "/webapp/jsp/calendar.jsp", :type => "GET", :vuln => ""},
			{ :path => "/webapp/wm/bc4j.jsp", :type => "GET", :vuln => "BC4J Admin Utility"},
			{ :path => "/webapp/wm/runtime.jsp", :type => "GET", :vuln => "BC4J Admin Utility"},
			{ :path => "/webcache/", :type => "GET", :vuln => ""},
			{ :path => "/webcache/webcache.xml", :type => "GET", :vuln => ""},
			{ :path => "/webcache/WebCacheDemo.html", :type => "GET", :vuln => ""},
			{ :path => "/WebCacheDemo.html", :type => "GET", :vuln => ""},
			{ :path => "/webcacheadmin", :type => "GET", :vuln => ""},
			{ :path => "/webcacheadmin?SCREEN_ID=CGA.CacheDump&ACTION=Submit&index=1&cache_dump_file=log.txt", :type => "GET", :vuln => ""},
			{ :path => "/webcalendar/", :type => "GET", :vuln => ""},
			{ :path => "/webservices/", :type => "GET", :vuln => ""},
			{ :path => "/webservices/beanTest?proxy_jar", :type => "GET", :vuln => ""},
			{ :path => "/webservices/beanTest?wsdl", :type => "GET", :vuln => ""},
			{ :path => "/webservices/statefulTest?proxy_jar", :type => "GET", :vuln => ""},
			{ :path => "/webservices/statefulTest?wsdl", :type => "GET", :vuln => ""},
			{ :path => "/webservices/statelessTest?proxy_jar", :type => "GET", :vuln => ""},
			{ :path => "/webservices/statelessTest?wsdl", :type => "GET", :vuln => ""},
			{ :path => "/webservices1/", :type => "GET", :vuln => ""},
			{ :path => "/webservices1/javacallin?invoke=to_string", :type => "GET", :vuln => ""},
			{ :path => "/webservices1/sqlstatement?getEmpBySalBeans&param0=500", :type => "GET", :vuln => ""},
			{ :path => "/webtools/", :type => "GET", :vuln => ""},
			{ :path => "/wireless/", :type => "GET", :vuln => ""},
			{ :path => "/xdk/", :type => "GET", :vuln => "Oracle XML Developers Kit Documentation"},
			{ :path => "/xdk/java/xsql/readme.html", :type => "GET", :vuln => "Oracle XML Developers Kit"},
			{ :path => "/xdk/doc/index.html", :type => "GET", :vuln => ""},
			{ :path => "/xsql/", :type => "GET", :vuln => "can have xsql demo pages which may allow you to run limited sql queries"},
			{ :path => "/xsql/java/xsql/demo/adhocsql/query.xsql?xml-stylesheet=none.xsl&sql=select+1+from+dual", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/lib/XSQLConfig.xml", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/java/xsql/demo/adhocsql/query.xsql?xmlstylesheet=none.xsl&sql=select+1+from+dual", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/java/xsql/demo/uri/uridemo.html", :type => "GET", :vuln => "Possibly Run SQL Queries"},
			{ :path => "/xsql/java/xsql/demo/insertxml/newsstorydemo.html", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/demo/adhocsql/query.xsql?xml-stylesheet=none.xsl&sql=select+1+from+dual", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/demo/airport/airport.xsql?xml-stylesheet=none", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/demo/adhocsql/query.xsql?sql=select+1+from+dual", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/adhocsql/query.xsql?xml-stylesheet=none.xsl&sql=select+1+from+dual", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/helloworld/helloworld.xsql", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/emp/emp.xsql?find=A", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/insclaim/xsqlov.htm", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/classerr/invalidclasses.xsql", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/doyouxml/doyouxml.xsql", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/empdept/empdept.xsql", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/airport/airport.htm", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/airport/airport.xsql?xml-stylesheet=airport.xsl", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/airport/airportSoap.html", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/adhocsql/sqltoxml.html", :type => "GET", :vuln => "Run SQL Commands CVE-2002-0569 "},
			{ :path => "/xsql/document/docdemo.html", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/insertxml/newsstorydemo.html", :type => "GET", :vuln => "XSQL Demos"},
			{ :path => "/xsql/svg/svgdemo.html", :type => "GET", :vuln => "XSQL Demos"},
			]

		demos = [
			{ :path => "/g11n/imap.html", :type => "GET", :vuln => "World of Books Demo"},
			{ :path => "/g11n/suppA/html/frame.html", :type => "GET", :vuln => "World of Books Demo"},
			{ :path => "/g11n/suppA/jsp/newBook.jsp", :type => "GET", :vuln => "World of Books Demo"},
			{ :path => "/g11n/suppB/html/frame.html", :type => "GET", :vuln => "World of Books Demo"},
			{ :path => "/g11n/suppB/jsp/newBook.jsp", :type => "GET", :vuln => "World of Books Demo"},
			{ :path => "/g11n/wob/jsp/welcome.jsp", :type => "GET", :vuln => "World of Books Demo"},
			{ :path => "/bmp/", :type => "GET", :vuln => ""},
			{ :path => "/bmp/global-web-application.xml", :type => "GET", :vuln => ""},
			{ :path => "/bmp/JSPClient.java", :type => "GET", :vuln => ""},
			{ :path => "/bmp/mime.types", :type => "GET", :vuln => ""},
			{ :path => "/bmp/README.txt", :type => "GET", :vuln => ""},
			{ :path => "/bmp/setconn.jsp", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljConnBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljConnBeanDemo.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljConnCacheBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljConnCacheBeanDemo.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljCursorBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljCursorBeanDemo.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/bmp/sqljdemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljIterator.sql.jsp", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljIterator.sql.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljSelectInto.sql.jsp", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljSelectInto.sql.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljSerialize.sql.jsp", :type => "GET", :vuln => ""},
			{ :path => "/bmp/SqljSerialize.sql.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/hellouser/hellouser.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/hellouser/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/info/info.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/info/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/jspstore/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/jspstore/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/lottery/lotto.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/lottery/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/demo/basic/simple/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/corba/CallCORBA.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/corba/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/corba/viewsrc/CallCORBA.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/corba/viewsrc/HelloCorbaWrapperBean.java.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/customtag/exampletag.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/customtag/index.htm", :type => "GET", :vuln => ""},
			{ :path => "/demo/customtag/viewsrc/ExampleLoopTag.java.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/customtag/viewsrc/ExampleLoopTagTEI.java.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/customtag/viewsrc/exampletag.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/customtag/viewsrc/exampletag.tld.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/ejb/CallEJB.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/ejb/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/ejb/viewsrc/CallEJB.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/ejb/viewsrc/EmployeeEJBWrapper.java.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/ojspext/events/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/ojspext/events/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/demo/ojspext/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/ojspext/jmltype/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/ojspext/jmltype/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/demo/ojspext/jspscope/scope.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/ojspext/jspscope/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/bean/ConnBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/bean/ConnCacheBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/bean/CursorBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/bean/DBBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/bean/viewsrc/ConnBeanDemo.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/bean/viewsrc/ConnCacheBeanDemo.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/bean/viewsrc/CursorBeanDemo.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/bean/viewsrc/DBBeanDemo.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/ConnCache1.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/ConnCache2.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/ConnCache3.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/JDBCQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/SimpleQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/UseHtmlQueryBean.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/viewsrc/ConnCache1.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/viewsrc/ConnCache2.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/viewsrc/ConnCache3.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/viewsrc/JDBCQuery.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/viewsrc/setupcache.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/viewsrc/SimpleQuery.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/jdbc/viewsrc/UseHtmlQueryBean.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/sqlj/SQLJIterator.sqljsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/sqlj/SQLJSelectInto.sqljsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/sqlj/viewsrc/SQLJIterator.sqljsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/sqlj/viewsrc/SQLJSelectInto.sqljsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/sample1.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/sample2.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/sample3.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/sample4.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/sample5.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/taglib.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/viewsrc/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/viewsrc/sample1.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/viewsrc/sample2.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/viewsrc/sample4.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/sql/tag/viewsrc/sample5.jsp.txt", :type => "GET", :vuln => ""},
			{ :path => "/demo/xml/helloxml/hello.jsp", :type => "GET", :vuln => ""},
			{ :path => "/demo/xml/helloxml/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/xml/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/xml/xmlquery/index.html", :type => "GET", :vuln => ""},
			{ :path => "/demo/xml/xmlquery/XMLQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/cal/calendar.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/cal/login.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/checkbox/check.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/checkbox/cresult.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/colors/clr.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/colors/colors.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/colors/cresult.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/dates/date.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/dates/date.jsp", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/error/er.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/error/error.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/forward/forward.jsp", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/forward/fwd.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/include/inc.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/jsptoserv/jsptoservlet.jsp", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/jsptoserv/jts.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/num/numguess.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/num/numguess.jsp", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/plugin/plugin.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/plugin/plugin.jsp", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/sessions/carts.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/sessions/crt.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/snp/snoop.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/jsp/snp/snoop.jsp", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/cookies.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/helloworld.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/index.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/reqheaders.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/reqinfo.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/reqparams.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/sessions.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/snoop.txt", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/examples/servlets/tojsp.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/OC4J_Demos", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/oc4jfeatures.html", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/servlet/CookieExample", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/servlet/HelloWorldExample", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/servlet/RequestHeaderExample", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/servlet/RequestInfoExample", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/servlet/RequestParamExample", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/servlet/SessionExample", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/servlet/SnoopServlet", :type => "GET", :vuln => ""},
			{ :path => "/j2ee/servlet/ToJSPServlet", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/hellouser/hellouser.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/hellouser/hellouser_jml.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/hellouser/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/info/info.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/info/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/jspstore/basic/addtobkt.gif", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/jspstore/basic/bg.gif", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/jspstore/basic/shop_again.gif", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/jspstore/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/jspstore/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/lottery/lotto.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/lottery/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/simple/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/simple/usebean.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/simple/welcome.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/basic/simple/welcomeuser.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/codenotes.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/data_in_html_and_email.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/ecSynopsis.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/fs/added.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/fs/additem.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/fs/fsSynopsis.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/objcache/objcache.jsp?testing4=101", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/objcache/synopsis.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/ocs/additem.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/ocs/ocsSynopsis.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/servletcode.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/servletSynopsis.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/setup.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/tagcode.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/xmldomcache.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/cache/xmldomcache.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/customtag/basic.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/customtag/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/customtag/looptag.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/customtag/xmlview.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ejbtags/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ejbtags/iterate.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ejbtags/usebean.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ejbtags/usebeanlocal.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/email/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/email/sendmail.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/beanDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/beanUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/dbBeanDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/dbDownloadIndx.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/dbTagDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/dbTagUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/dbUploadIndex.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/fileDownloadIndex.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/fileindex.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/fileUploadIndex.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/maxfiles.jsp?action=uploadForm.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/maxfiles.jsp?action=uploadForm.jsp&nextaction=dbBeanUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/maxfiles.jsp?action=uploadForm.jsp&nextaction=dbTagUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/maxfiles.jsp?action=uploadForm.jsp&nextaction=tagUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/tagDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/tagUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/uploadForm.html?nextaction=null&MaxFiles=1&Submit=OK", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/uploadForm.jsp?nextaction=dbBeanUploadExample.jsp&MaxFiles=1&Submit=OK", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/uploadForm.jsp?nextaction=dbTagUploadExample.jsp&MaxFiles=5&Submit=OK", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/fileaccess/uploadForm.jsp?nextaction=tagUploadExample.jsp&MaxFiles=1&Submit=OK", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/iterate/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/iterate/iterateSample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jesi/fragment.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jesi/include.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jesi/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jesi/invalidation.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jesi/invalidation2.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jesi/personalize.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jesi/setup.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jspdynamicws/dynamicws.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jspdynamicws/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jspdynamicws/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jspwsdemo/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jspwsdemo/Readme.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jspwsdemo/wsclient.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jspxmlview/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jspxmlview/lottoXml.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/jstl_instructions.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/misc/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/misc/jsptld_11_2_12.xsl", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ojspext/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ojspext/jmltype/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ojspext/jmltype/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ojspext/jspscope/scope.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/ojspext/jspscope/synopsis.htm", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/oracle-standard.ear", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/personalization/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/personalization/recommend.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/personalization/record.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/personalization/setup.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/personalization/stateless.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/personalization/tagdemodriver.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/hellouser/hellouser.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/hellouser/hellouser_jml.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/info/info.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/jspstore/cart.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/jspstore/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/lottery/lotto.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/simple/usebean.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/simple/welcome.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/basic/simple/welcomeuser.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/fs/added.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/fs/listitem.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/fs/seeitems.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/objcache/objcache.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/ocs/added.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/ocs/listitem.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/ocs/seeitems.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/servletcode.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/tagcode.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/cache/xmldomcache.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/demoUtil.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/ejbtags/iterate.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/ejbtags/usebean.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/ejbtags/usebeanlocal.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/email/sendmail.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/beanDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/beanDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/beanUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/dbBeanDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/dbBeanUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/dbTagDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/dbTagUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/maxfiles.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/tagDownloadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/tagUploadExample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/uploadForm.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/fileaccess/uploadForm.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/iterate/iterateSample.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/jesi/fragment.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/jesi/include.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/jesi/invalidation.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/jesi/invalidation2.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/jesi/personalize.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/jspdynamicws/dynamicws.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/jspwsdemo/wsclient.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/jspxmlview/lottoXml.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/ojspext/jmltype/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/ojspext/jspscope/scope.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/endsession.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/evaluateitem.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/getcrosssellrecommendations.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/getrecsasnext.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/getrecsinlist.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/recommend.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/record.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/recorddemographic.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/recordnavigation.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/recordpurchase.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/recordrating.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/removedemographicrecord.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/removenavigationrecord.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/removepurchaserecord.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/removeratingrecord.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/selectfromhpasnext.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/selectfromhpinlist.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/setvisitortocustomer.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/stateless.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/stateless_close.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/stateless_get.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/personalization/tagdemodriver.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/bean/ConnBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/bean/ConnCacheBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/bean/CursorBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/bean/DBBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/jdbc/ConnCache1.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/jdbc/ConnCache2.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/jdbc/JDBCQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/jdbc/setupcache.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/jdbc/SimpleQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/jdbc/UseHtmlQueryBean.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/sqlj/SQLJIterator.sqljsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/sqlj/SQLJSelectInto.sqljsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample1.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample10.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample11.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample2.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample3.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample4.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample5.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample6.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample7.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample8.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/sample9.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/sql/tag/style/rowset.xsl", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/caTraffic/bean/CATrafficServiceProxy.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/caTraffic/bean/CATrafficServiceProxy.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/demoPkg/DemoCacheServlet.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoEntity.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoEntityEJB.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoEntityHome.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoSession.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoSessionEJB.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoSessionHome.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoSessionLocal.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoSessionLocalEJB.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/ejbdemo/DemoSessionLocalHome.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/examples/ExampleLoopTag.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/examples/ExampleLoopTagTEI.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/examples/RStrArray.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/examples/StrArray.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/examples/WStrArray.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/exampletag.tld", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/oracle/j2ee/ws/client/impl/WSClientBean.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/Oracle/j2ee/ws/client/impl/WSClientBean.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/Oracle/jsp/sample/event/PageEventDispatcher.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/oracle/taglib/IterateTag.java", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/src/test-policy.cpd", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/trafficCA/CATraffic.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/WEB-INF/iteratetag.tld", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/wstags/desc.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/wstags/dynamicws.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/xml/helloxml/hello.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/xml/helloxml/style/hello.xsl", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/xml/xmldom/xmldom.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/servlet/ViewSrc/xml/xmlquery/XMLQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/setup.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/bean/ConnBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/bean/ConnCacheBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/bean/CursorBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/bean/DBBeanDemo.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/bean/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/index.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/jdbc/ConnCache1.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/jdbc/ConnCache2.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/jdbc/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/jdbc/JDBCQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/jdbc/SimpleQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/jdbc/UseHtmlQueryBean.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/sqlj/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/sqlj/SQLJIterator.sqljsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/sqlj/SQLJSelectInto.sqljsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/indx3.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample1.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample10.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample11.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample2.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample3.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample4.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample5.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample6.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample7.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample8.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/sample9.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/sql/tag/taglib.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/trafficCA/CATraffic.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/trafficCA/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/wstags/dynamicws.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/wstags/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/xml/helloxml/hello.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/xml/helloxml/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/xml/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/xml/xmldom/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/xml/xmldom/xmldom.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/xml/xmlquery/index.html", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/xml/xmlquery/XMLQuery.jsp", :type => "GET", :vuln => ""},
			{ :path => "/ojspdemos/xss.html", :type => "GET", :vuln => ""},
			]

		checks.each do | check |
			
			res = send_request_raw({
				'uri'     => check[:path],
				'method'  => check[:type],
			}, 30)

				if (res.nil?)
					print_error("No response for #{rhost}:#{rport}")
				elsif (res and res.code == 200)
					print_good("Found: #{check[:path]} --> Vuln: #{check[:vuln]}")
						# Store URLs we receive 200 for
						report_note(
							:update	=> :unique_data,
							:host         => ip,
							:port         => datastore['RPORT'],
							:proto       => 'tcp',
							:type        => 'oracle.http.portal', 
							:data        =>   {:code => res.code, :url => check[:path]}  
								)
				elsif (res and res.code == 401)
					print_status("Received 401 for: #{check[:path]} --> Vuln: #{check[:vuln]}")
				elsif (res and res.code == 302 or res.code == 301)
					print_good("Received 302 to #{res.headers['Location']} for #{check[:path]}")
				else
					if datastore['VERBOSE']
						print_status("Received #{res.code} for #{check[:path]}") #debug
					else
						''
					end	
				end
			end

				
		if datastore['DEMOS']
			print_status("\nRunning checks for common demo pages against #{rhost}:#{rport}\n")
				
			demos.each do | check |
			res = send_request_raw({
				'uri'     => check[:path],
				'method'  => check[:type],
			}, 30)
			if (res.nil?)
					print_error("No response for #{rhost}:#{rport}")
				elsif (res and res.code == 200)
					print_good("Found: #{check[:path]} --> Vuln: #{check[:vuln]}")
					# Store URLs we receive 200 for
						report_note(
							:update	=> :unique_data,
							:host         => ip,
							:port         => datastore['RPORT'],
							:proto       => 'tcp',
							:type        => 'oracle.http.portal', 
							:data        =>  {:code => res.code, :url => check[:path]} 
								)
				elsif (res and res.code == 401)
					print_good("Found: #{check[:path]} --> Vuln: #{check[:vuln]}")
				elsif (res and res.code == 302 or res.code == 301)
					print_good("Received 302 to #{res.headers['Location']} for #{check[:path]}")
				else
					if datastore['VERBOSE']
						print_status("Received #{res.code} for #{check[:path]}") #debug
					else
						''
					end	
				end
			end
		end
		end
			rescue ::Rex::ConnectionRefused, ::Rex::HostUnreachable, ::Rex::ConnectionTimeout, Rex::ConnectionError
			rescue Timeout::Error, Errno::EINVAL, Errno::ECONNRESET, EOFError, Errno::ECONNABORTED, Errno::ECONNREFUSED, Errno::EHOSTUNREACH =>e
			puts e.message
	end

#Oracle Reports the server variable is required
#{ :path => "/reports/rwservlet/getjobid7?server=myrep", :type => "GET", :vuln => "Oracle Reports URLS with sensitive info -- the number may need to change"},
#{ :path => "/reports/rwservlet/getjobid4?server=myrep", :type => "GET", :vuln => "Oracle Reports URLS with sensitive info -- the number may need to change"},
#{ :path => "/BPELConsole/default/processLog.jsp?processId=*&revisionTag=*&processName=ssssssssssssssssssss\"\>\<script\>alert()\<\/script\>&eventType=all&eventDate=all", :type => "GET", :vuln => "XSS Vuln -- CVE-2010-3581"},
