##
# This file is part of the Metasploit Framework and may be subject to 
# redistribution and commercial restrictions. Please see the Metasploit
# Framework web site for more information on licensing and terms of use.
# http://metasploit.com/framework/
##

require 'msf/core'


class Metasploit3 < Msf::Auxiliary
	
	# Exploit mixins should be called first
	include Msf::Exploit::Remote::HttpClient
	# Scanner mixin should be near last
	include Msf::Auxiliary::Scanner

	def initialize
		super(
			'Name'        => 'Oracle Application Server Detection',
			'Version'     => '$Revision:  $',
			'Description' => 'This scans for common ORACLE Database Access Desriptors (DAD)',
			'Author'      => 'CG' ,
			'License'     => MSF_LICENSE,
			'References'	=>
				[
					[ 'URL', 'http://www.owasp.org/index.php/Testing_for_Oracle' ]
				]
			)
		register_options(
			[
				OptBool.new('VERBOSE', [ true, 'Show 404s and other errors', true ])
			], self.class)
	end

	def run_host(ip)
#time to blow up the IPS/IDS :-)
		dad = [	
			{ :path => "/", :type => "GET"},			
			{ :path => "/pls", :type => "GET"},
			{ :path => "/pls/", :type => "GET"},
			{ :path => "/apex", :type => "GET"},
			{ :path => "/pls/adm", :type => "GET"},
			{ :path => "/pls/admin", :type => "GET"},
			{ :path => "/pls/admin_/", :type => "GET"},
			{ :path => "/pls/apex", :type => "GET"},
			{ :path => "/pls/apex_prod", :type => "GET"},
			{ :path => "/pls/APEX_PROD", :type => "GET"},
			{ :path => "/pls/app", :type => "GET"},
			{ :path => "/pls/asktom", :type => "GET"},
			{ :path => "/pls/auth", :type => "GET"},
			{ :path => "/pls/bprod", :type => "GET"},
			{ :path => "/pls/cameo", :type => "GET"},
			{ :path => "/pls/capital", :type => "GET"},
			{ :path => "/pls/capitol", :type => "GET"},
			{ :path => "/pls/cbw", :type => "GET"},
			{ :path => "/pls/cfg", :type => "GET"},
			{ :path => "/pls/classic", :type => "GET"},
			{ :path => "/pls/coes", :type => "GET"},
			{ :path => "/pls/consulta817", :type => "GET"},
			{ :path => "/pls/cs_wf", :type => "GET"},
			{ :path => "/pls/cuesp", :type => "GET"},
			{ :path => "/pls/dad", :type => "GET"},
			{ :path => "/pls/dad_", :type => "GET"},
			{ :path => "/pls/dad_user", :type => "GET"},
			{ :path => "/pls/dad_des", :type => "GET"},
			{ :path => "/pls/dayt", :type => "GET"},
			{ :path => "/pls/db", :type => "GET"},
			{ :path => "/pls/design", :type => "GET"},
			{ :path => "/pls/designdev", :type => "GET"},
			{ :path => "/pls/dipa", :type => "GET"},
			{ :path => "/pls/drip", :type => "GET"},
			{ :path => "/pls/ecominternet", :type => "GET"},
			{ :path => "/pls/enetrixp", :type => "GET"},
			{ :path => "/pls/ecover", :type => "GET"},
			{ :path => "/pls/ense_noti", :type => "GET"},
			{ :path => "/pls/fieldlink", :type => "GET"},
			{ :path => "/pls/flexp", :type => "GET"},
			{ :path => "/pls/gardena", :type => "GET"},
			{ :path => "/pls/geo", :type => "GET"},
			{ :path => "/pls/GEO", :type => "GET"},
			{ :path => "/pls/gprprd", :type => "GET"},
			{ :path => "/pls/gss", :type => "GET"},
			{ :path => "/pls/guber", :type => "GET"},
			{ :path => "/pls/hb", :type => "GET"},
			{ :path => "/pls/hr", :type => "GET"},		
			{ :path => "/pls/hcprd", :type => "GET"},
			{ :path => "/pls/htmldb", :type => "GET"},
			{ :path => "/pls/hospital", :type => "GET"},
			{ :path => "/pls/icbap", :type => "GET"},
			{ :path => "/pls/ieptrndb", :type => "GET"},
			{ :path => "/pls/interportal", :type => "GET"},
			{ :path => "/pls/izs_bt", :type => "GET"},
			{ :path => "/pls/jobs", :type => "GET"},
			{ :path => "/pls/mae", :type => "GET"},
			{ :path => "/pls/mhcprd", :type => "GET"},
			{ :path => "/pls/mycms", :type => "GET"},
			{ :path => "/pls/namicp", :type => "GET"},
			{ :path => "/pls/nvp", :type => "GET"},
			{ :path => "/pls/notes", :type => "GET"},
			{ :path => "/pls/nspep", :type => "GET"},
			{ :path => "/pls/omedev", :type => "GET"},
			{ :path => "/pls/oemdev", :type => "GET"},
			{ :path => "/pls/online", :type => "GET"},
			{ :path => "/pls/open", :type => "GET"},
			{ :path => "/pls/orasso", :type => "GET"},
			{ :path => "/pls/owa", :type => "GET"},
			{ :path => "/pls/owm", :type => "GET"},
			{ :path => "/pls/ows-bin", :type => "GET"},
			{ :path => "/pls/ows-bin/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/app", :type => "GET"},
			{ :path => "/pls/ows-bin/app/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/banking", :type => "GET"},
			{ :path => "/pls/ows-bin/banking/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/cartx", :type => "GET"},
			{ :path => "/pls/ows-bin/cartx/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/cartx/owa", :type => "GET"},	
			{ :path => "/pls/ows-bin/cartx/owa/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/dad", :type => "GET"},
			{ :path => "/pls/ows-bin/dad/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/db", :type => "GET"},
			{ :path => "/pls/ows-bin/db/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/htmldb", :type => "GET"},
			{ :path => "/pls/ows-bin/htmldb/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/myapp", :type => "GET"},
			{ :path => "/pls/ows-bin/myapp/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/mydad", :type => "GET"},
			{ :path => "/pls/ows-bin/mydad/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/orasso", :type => "GET"},
			{ :path => "/pls/ows-bin/orasso/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/online", :type => "GET"},
			{ :path => "/pls/ows-bin/online/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/owa", :type => "GET"},
			{ :path => "/pls/ows-bin/owa/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/ows-binqlapp", :type => "GET"},
			{ :path => "/pls/ows-bin/ows-binqlapp/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/portal", :type => "GET"},
			{ :path => "/pls/ows-bin/portal/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/portal2", :type => "GET"},
			{ :path => "/pls/ows-bin/portal2/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/portal30", :type => "GET"},
			{ :path => "/pls/ows-bin/portal30/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/portal30_sso", :type => "GET"},
			{ :path => "/pls/ows-bin/portal30_sso/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/portal306", :type => "GET"},
			{ :path => "/pls/ows-bin/portal306/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/portal309", :type => "GET"},
			{ :path => "/pls/ows-bin/portal309/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/qa", :type => "GET"},
			{ :path => "/pls/ows-bin/qa/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/real", :type => "GET"},
			{ :path => "/pls/ows-bin/real/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/sample", :type => "GET"},
			{ :path => "/pls/ows-bin/sample/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/simpledad", :type => "GET"},
			{ :path => "/pls/ows-bin/simpledad/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/ssodad", :type => "GET"},
			{ :path => "/pls/ows-bin/ssodad/admin_/", :type => "GET"},
			{ :path => "/pls/ows-bin/test", :type => "GET"},
			{ :path => "/pls/ows-bin/test/admin_/", :type => "GET"},
			{ :path => "/pls/p100", :type => "GET"},
			{ :path => "/pls/psi", :type => "GET"},
			{ :path => "/pls/pcsso", :type => "GET"},
			{ :path => "/pls/pin_adm", :type => "GET"},
			{ :path => "/pls/pin_admin", :type => "GET"},
			{ :path => "/pls/plq-dad", :type => "GET"},
			{ :path => "/pls/portal", :type => "GET"},
			{ :path => "/pls/portal/portal.home", :type => "GET"},
			{ :path => "/pls/portal/PORTAL.home", :type => "GET"},
			{ :path => "/pls/portal/PORTAL.wwsec_app_priv.login", :type => "GET"},
			{ :path => "/pls/portal/uri", :type => "GET"},
			{ :path => "/pls/portal/uri/page", :type => "GET"},
			{ :path => "/pls/portal2", :type => "GET"},
			{ :path => "/pls/portal20", :type => "GET"},
			{ :path => "/pls/portal30", :type => "GET"},
			{ :path => "/pls/portal30_sso", :type => "GET"},
			{ :path => "/pls/portal306", :type => "GET"},
			{ :path => "/pls/portal309", :type => "GET"},
			{ :path => "/pls/portallive", :type => "GET"},
			{ :path => "/pls/portallive/uri", :type => "GET"},
			{ :path => "/pls/portalhtml", :type => "GET"},
			{ :path => "/pls/prd", :type => "GET"},
			{ :path => "/pls/PRD", :type => "GET"},
			{ :path => "/pls/prod", :type => "GET"},
			{ :path => "/pls/PROD", :type => "GET"},
			{ :path => "/pls/PRODUCTION", :type => "GET"},
			{ :path => "/pls/production", :type => "GET"},
			{ :path => "/pls/PROD_portal30", :type => "GET"},
			{ :path => "/pls/prod_portal30", :type => "GET"},
			{ :path => "/pls/proxy10g", :type => "GET"},
			{ :path => "/pls/proxy9i", :type => "GET"},
			{ :path => "/pls/psso", :type => "GET"},
			{ :path => "/pls/psso_portal30", :type => "GET"},
			{ :path => "/pls/psso_portal30", :type => "GET"},
			{ :path => "/pls.reg", :type => "GET"},
			{ :path => "/pls/registration", :type => "GET"},
			{ :path => "/pls/rsh", :type => "GET"},
			{ :path => "/pls/sac", :type => "GET"},
			{ :path => "/pls/sc", :type => "GET"},
			{ :path => "/pls/sfrs", :type => "GET"},
			{ :path => "/pls/sgc", :type => "GET"},
			{ :path => "/pls/siex", :type => "GET"},
			{ :path => "/pls/sample", :type => "GET"},
			{ :path => "/pls/sample/admin_/", :type => "GET"},
			{ :path => "/pls/sample/sample.home", :type => "GET"},
			{ :path => "/pls/sampledad", :type => "GET"},
			{ :path => "/pls/sampledad/sample.home", :type => "GET"},
			{ :path => "/pls/scott", :type => "GET"},
			{ :path => "/pls/servlet", :type => "GET"},
			{ :path => "/pls/simpledad", :type => "GET"},
			{ :path => "/pls/simpledad/sample.home", :type => "GET"},
			{ :path => "/pls/srastdp", :type => "GET"},
			{ :path => "/pls/sso", :type => "GET"},
			{ :path => "/pls/ssodad", :type => "GET"},
			{ :path => "/pls/ssodad/sample.home", :type => "GET"},
			{ :path => "/pls/stats", :type => "GET"},
			{ :path => "/pls/test", :type => "GET"},
			{ :path => "/pls/utils", :type => "GET"},
			{ :path => "/pls/UTILS", :type => "GET"},
			{ :path => "/pls/utility", :type => "GET"},
			{ :path => "/pls/UTILITY", :type => "GET"},
			{ :path => "/pls/uschamberp", :type => "GET"},
			{ :path => "/pls/velo", :type => "GET"},
			{ :path => "/pls/wbap", :type => "GET"},
			{ :path => "/pls/webapp", :type => "GET"},
			{ :path => "/pls/webdb", :type => "GET"},
			{ :path => "/pls/WebDB", :type => "GET"},
			{ :path => "/pls/webpls", :type => "GET"},
			{ :path => "/pls/webprod", :type => "GET"},
			{ :path => "/pls/web_prod", :type => "GET"},
			{ :path => "/pls/web_igate", :type => "GET"},
			{ :path => "/pls/web_prod-plq-dad", :type => "GET"},
			{ :path => "/pls/webuser", :type => "GET"},
			{ :path => "/pls/web_user", :type => "GET"},
			{ :path => "/pls/wf", :type => "GET"},
			{ :path => "/pls/wfa", :type => "GET"},
			{ :path => "/pls/workflow", :type => "GET"},
			{ :path => "/pls/Workflow", :type => "GET"},
			{ :path => "/pls/wlnp", :type => "GET"},
			{ :path => "/pls/www", :type => "GET"},
			{ :path => "/pls/wwwbks", :type => "GET"},
			{ :path => "/pls/wzec", :type => "GET"},
			{ :path => "/pls/xdb", :type => "GET"},
			{ :path => "/pls/xr", :type => "GET"},
			{ :path => "/portal", :type => "GET"},
			{ :path => "/portal/", :type => "GET"},
			{ :path => "/portal/page", :type => "GET"},
			{ :path => "/portal/page/", :type => "GET"},
			{ :path => "/portal/page/portal", :type => "GET"},
			{ :path => "/portal/page/portal/", :type => "GET"},
			{ :path => "/portal/pls", :type => "GET"},
			{ :path => "/portal/pls/", :type => "GET"},
			{ :path => "/portal/pls/portal", :type => "GET"},
			{ :path => "/portal/pls/portal/", :type => "GET"},
			{ :path => "/portal/pls/portal/portal.home", :type => "GET"},
			{ :path => "/portal/pls/portal/PORTAL.home", :type => "GET"},
			{ :path => "/portal/pls/portal/PORTAL.wwsec_app_priv.login", :type => "GET"},
			{ :path => "/portal/portal2", :type => "GET"},
			{ :path => "/portal/portal2/", :type => "GET"},
			{ :path => "/portal2", :type => "GET"},
			{ :path => "/portal2/", :type => "GET"},
			{ :path => "/portal/portal20", :type => "GET"},
			{ :path => "/portal/portal20/", :type => "GET"},
			{ :path => "/portal20", :type => "GET"},
			{ :path => "/portal20/", :type => "GET"},
			{ :path => "/portal/portal30", :type => "GET"},
			{ :path => "/portal/portal30/", :type => "GET"},
			{ :path => "/portal30", :type => "GET"},
			{ :path => "/portal30/", :type => "GET"},
			{ :path => "/portal/portal30_sso", :type => "GET"},
			{ :path => "/portal/portal30_sso/", :type => "GET"},
			{ :path => "/portal30_sso", :type => "GET"},
			{ :path => "/portal30_sso/", :type => "GET"},
			{ :path => "/portal/portal306", :type => "GET"},
			{ :path => "/portal/portal306/", :type => "GET"},
			{ :path => "/portal306", :type => "GET"},
			{ :path => "/portal306/", :type => "GET"},
			{ :path => "/portal/portal309", :type => "GET"},
			{ :path => "/portal/portal309/", :type => "GET"},
			{ :path => "/portal309", :type => "GET"},
			{ :path => "/portal309/", :type => "GET"},
			{ :path => "/admin", :type => "GET"},
			{ :path => "/admin/", :type => "GET"},
			{ :path => "/apex_prod", :type => "GET"},
			{ :path => "/apex_prod/", :type => "GET"},
			{ :path => "/app", :type => "GET"},
			{ :path => "/app/", :type => "GET"},
			{ :path => "/auth", :type => "GET"},
			{ :path => "/auth/", :type => "GET"},
			{ :path => "/bprod", :type => "GET"},
			{ :path => "/bprod/", :type => "GET"},
			{ :path => "/classic", :type => "GET"},
			{ :path => "/classic/", :type => "GET"},
			{ :path => "/coes", :type => "GET"},
			{ :path => "/coes/", :type => "GET"},
			{ :path => "/cuesp", :type => "GET"},
			{ :path => "/cuesp/", :type => "GET"},
			{ :path => "/dad", :type => "GET"},
			{ :path => "/dad/", :type => "GET"},
			{ :path => "/dad_", :type => "GET"},
			{ :path => "/dad_/", :type => "GET"},
			{ :path => "/dad_user", :type => "GET"},
			{ :path => "/dad_user/", :type => "GET"},
			{ :path => "/dad_des", :type => "GET"},
			{ :path => "/dad_des/", :type => "GET"},
			{ :path => "/dav", :type => "GET"},
			{ :path => "/dav/", :type => "GET"},
			{ :path => "/dav_portal", :type => "GET"},
			{ :path => "/dav_portal/", :type => "GET"},
			{ :path => "/dav_portal/portal/", :type => "GET"},
			{ :path => "/dav_public", :type => "GET"},
			{ :path => "/dav_public/", :type => "GET"},
			{ :path => "/dayt", :type => "GET"},
			{ :path => "/dayt/", :type => "GET"},
			{ :path => "/db", :type => "GET"},
			{ :path => "/db/", :type => "GET"},
			{ :path => "/dipa", :type => "GET"},
			{ :path => "/dipa/", :type => "GET"},
			{ :path => "/drip", :type => "GET"},
			{ :path => "/drip/", :type => "GET"},
			{ :path => "/hb", :type => "GET"},
			{ :path => "/hb/", :type => "GET"},
			{ :path => "/htmldb", :type => "GET"},
			{ :path => "/htmldb/", :type => "GET"},	
			{ :path => "/interportal", :type => "GET"},
			{ :path => "/interportal/", :type => "GET"},
			{ :path => "/mycms", :type => "GET"},
			{ :path => "/mycms/", :type => "GET"},
			{ :path => "/online", :type => "GET"},
			{ :path => "/online/", :type => "GET"},
			{ :path => "/orasso", :type => "GET"},
			{ :path => "/orasso/", :type => "GET"},
			{ :path => "/owa", :type => "GET"},
			{ :path => "/owa/", :type => "GET"},
			{ :path => "/owm", :type => "GET"},
			{ :path => "/owm/", :type => "GET"},
			{ :path => "/ows-bin", :type => "GET"},
			{ :path => "/ows-bin/", :type => "GET"},
			{ :path => "/ows-bin/admin_/", :type => "GET"},
			{ :path => "/ows-bin/app", :type => "GET"},
			{ :path => "/ows-bin/app/admin_/", :type => "GET"},
			{ :path => "/ows-bin/banking", :type => "GET"},
			{ :path => "/ows-bin/banking/admin_/", :type => "GET"},
			{ :path => "/ows-bin/cartx", :type => "GET"},
			{ :path => "/ows-bin/cartx/admin_/", :type => "GET"},
			{ :path => "/ows-bin/cartx/owa", :type => "GET"},	
			{ :path => "/ows-bin/cartx/owa/admin_/", :type => "GET"},
			{ :path => "/ows-bin/dad", :type => "GET"},
			{ :path => "/ows-bin/dad/admin_/", :type => "GET"},
			{ :path => "/ows-bin/db", :type => "GET"},
			{ :path => "/ows-bin/db/admin_/", :type => "GET"},
			{ :path => "/ows-bin/htmldb", :type => "GET"},
			{ :path => "/ows-bin/htmldb/admin_/", :type => "GET"},
			{ :path => "/ows-bin/myapp", :type => "GET"},
			{ :path => "/ows-bin/myapp/admin_/", :type => "GET"},
			{ :path => "/ows-bin/mydad", :type => "GET"},
			{ :path => "/ows-bin/mydad/admin_/", :type => "GET"},
			{ :path => "/ows-bin/orasso", :type => "GET"},
			{ :path => "/ows-bin/orasso/admin_/", :type => "GET"},
			{ :path => "/ows-bin/online", :type => "GET"},
			{ :path => "/ows-bin/online/admin_/", :type => "GET"},
			{ :path => "/ows-bin/owa", :type => "GET"},
			{ :path => "/ows-bin/owa/admin_/", :type => "GET"},
			{ :path => "/ows-bin/ows-binqlapp", :type => "GET"},
			{ :path => "/ows-bin/ows-binqlapp/admin_/", :type => "GET"},
			{ :path => "/ows-bin/portal", :type => "GET"},
			{ :path => "/ows-bin/portal/admin_/", :type => "GET"},
			{ :path => "/ows-bin/portal2", :type => "GET"},
			{ :path => "/ows-bin/portal2/admin_/", :type => "GET"},
			{ :path => "/ows-bin/portal30", :type => "GET"},
			{ :path => "/ows-bin/portal30/admin_/", :type => "GET"},
			{ :path => "/ows-bin/portal30_sso", :type => "GET"},
			{ :path => "/ows-bin/portal30_sso/admin_/", :type => "GET"},
			{ :path => "/ows-bin/portal306", :type => "GET"},
			{ :path => "/ows-bin/portal306/admin_/", :type => "GET"},
			{ :path => "/ows-bin/portal309", :type => "GET"},
			{ :path => "/ows-bin/portal309/admin_/", :type => "GET"},
			{ :path => "/ows-bin/qa", :type => "GET"},
			{ :path => "/ows-bin/qa/admin_/", :type => "GET"},
			{ :path => "/ows-bin/real", :type => "GET"},
			{ :path => "/ows-bin/real/admin_/", :type => "GET"},
			{ :path => "/ows-bin/sample", :type => "GET"},
			{ :path => "/ows-bin/sample/admin_/", :type => "GET"},
			{ :path => "/ows-bin/simpledad", :type => "GET"},
			{ :path => "/ows-bin/simpledad/admin_/", :type => "GET"},
			{ :path => "/ows-bin/ssodad", :type => "GET"},
			{ :path => "/ows-bin/ssodad/admin_/", :type => "GET"},
			{ :path => "/ows-bin/test", :type => "GET"},
			{ :path => "/ows-bin/test/admin_/", :type => "GET"},
			{ :path => "/oa_servlets/AppsLogin", :type => "GET"},
			{ :path => "/pcsso", :type => "GET"},
			{ :path => "/pcsso/", :type => "GET"},
			{ :path => "/plq-dad", :type => "GET"},
			{ :path => "/plq-dad/", :type => "GET"},
			{ :path => "/plsql", :type => "GET"},
			{ :path => "/plsql/", :type => "GET"},
			{ :path => "/plsql-dad", :type => "GET"},
			{ :path => "/plsql-dad/", :type => "GET"},
			{ :path => "/plsqlapp", :type => "GET"},
			{ :path => "/plsqlapp/", :type => "GET"},
			{ :path => "/portalhtml", :type => "GET"},
			{ :path => "/portalhtml/", :type => "GET"},
			{ :path => "/prd", :type => "GET"},
			{ :path => "/prd/", :type => "GET"},
			{ :path => "/PRD", :type => "GET"},
			{ :path => "/PRD/", :type => "GET"},
			{ :path => "/prod", :type => "GET"},
			{ :path => "/prod/", :type => "GET"},
			{ :path => "/PROD", :type => "GET"},
			{ :path => "/PROD/", :type => "GET"},
			{ :path => "/prod_portal30", :type => "GET"},
			{ :path => "/prod_portal30/", :type => "GET"},
			{ :path => "/PROD_portal30", :type => "GET"},
			{ :path => "/PROD_portal30/", :type => "GET"},
			{ :path => "/proxy10g", :type => "GET"},
			{ :path => "/proxy10g/", :type => "GET"},
			{ :path => "/proxy9i", :type => "GET"},
			{ :path => "/proxy9i/", :type => "GET"},
			{ :path => "/psso", :type => "GET"},
			{ :path => "/psso/", :type => "GET"},
			{ :path => "/psso_portal30", :type => "GET"},
			{ :path => "/psso_portal30/", :type => "GET"},
			{ :path => "/ptg", :type => "GET"},
			{ :path => "/ptg/", :type => "GET"},
			{ :path => "/ptg/rm", :type => "GET"},
			{ :path => "/ptg/rm/", :type => "GET"},
			{ :path => "/sample", :type => "GET"},
			{ :path => "/sample/", :type => "GET"},
			{ :path => "/sampledad", :type => "GET"},
			{ :path => "/sampledad/", :type => "GET"},
			{ :path => "/sampledad/sample.home", :type => "GET"},
			{ :path => "/servlet", :type => "GET"},
			{ :path => "/servlet/", :type => "GET"},
			{ :path => "/servlet/page", :type => "GET"},
			{ :path => "/servlet/page/", :type => "GET"},
			{ :path => "/servlet/RepositoryServlet", :type => "GET"},
			{ :path => "/servlet/RepositoryServlet/", :type => "GET"},
			{ :path => "/servlet/RepositoryServlet/portal", :type => "GET"},
			{ :path => "/servlet/RepositoryServlet/portal/", :type => "GET"},
			{ :path => "/simpledad", :type => "GET"},
			{ :path => "/simpledad/", :type => "GET"},
			{ :path => "/simpledad/sample.home", :type => "GET"},
			{ :path => "/sso", :type => "GET"},
			{ :path => "/sso/", :type => "GET"},
			{ :path => "/ssodad", :type => "GET"},
			{ :path => "/ssodad/", :type => "GET"},
			{ :path => "/ssodad/sample.home", :type => "GET"},
			{ :path => "/test", :type => "GET"},
			{ :path => "/test/", :type => "GET"},
			{ :path => "/utils", :type => "GET"},
			{ :path => "/utils/", :type => "GET"},
			{ :path => "/UTILS", :type => "GET"},
			{ :path => "/UTILS/", :type => "GET"},
			{ :path => "/webapp", :type => "GET"},
			{ :path => "/webapp/", :type => "GET"},
			{ :path => "/webpls", :type => "GET"},
			{ :path => "/webpls/", :type => "GET"},
			{ :path => "/webprod", :type => "GET"},
			{ :path => "/webprod/", :type => "GET"},
			{ :path => "/web_prod", :type => "GET"},
			{ :path => "/web_prod/", :type => "GET"},
			{ :path => "/web_prod_plq-dad", :type => "GET"},
			{ :path => "/web_prod-plq-dad/", :type => "GET"},
			{ :path => "/webuser", :type => "GET"},
			{ :path => "/webuser/", :type => "GET"},
			{ :path => "/web_user", :type => "GET"},
			{ :path => "/web_user/", :type => "GET"},
			{ :path => "/www", :type => "GET"},
			{ :path => "/www/", :type => "GET"},
			{ :path => "/xdb", :type => "GET"},
			{ :path => "/xdb/", :type => "GET"},
			{ :path => "/xr", :type => "GET"},
			{ :path => "/xr/", :type => "GET"},
			]
		
		dad.each do | check |

		begin	
			res = send_request_raw({
				'uri'     => check[:path],
				'method'  => check[:type],
			}, 30)

			if (res.nil?)
				print_error("No response for #{rhost}:#{rport} #{check[:path]}")
			elsif (res.code == 200)
				print_good("Received #{res.code} for DAD: #{check[:path]}")
			elsif(res.code == 302 or res.code == 301)
				print_good("Received #{res.code} for DAD: #{check[:path]} --> Redirect to #{res.headers['Location']}")
			else
				if datastore['VERBOSE']
					print_status("#{res.code} for #{check[:path]}")
				else
					''
				end
			end

		rescue ::Rex::ConnectionRefused, ::Rex::HostUnreachable, ::Rex::ConnectionTimeout
		rescue ::Timeout::Error, ::Errno::EPIPE
		end
		end
	end
end
